config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('catalog/', include('users.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path
from . import views
from .views import Register, PersonalAreaView, DeleteUserView, UpdateUser, IndexView, \
    QuestionFullView

urlpatterns = [
    path('', IndexView.as_view(template_name="index.html"), name='index'),
    path('signup/', Register.as_view(), name='signup'),
    path('personal_area/', PersonalAreaView.as_view(), name='personal_area'),
    path('delete_user/<int:pk>/', DeleteUserView.as_view(), name='delete_user'),
    path('update_user/<int:pk>/', UpdateUser.as_view(), name='update_user'),
    path('question_info/<int:pk>/', QuestionFullView.as_view(), name='info_question'),
    path('vote/<int:question_id>/', views.vote, name='vote'),
    path('result/<int:pk>/', views.ResultsView.as_view(), name='result_question'),
]

users/models.py
from datetime import timezone, datetime, date, timedelta
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    id = models.AutoField(primary_key=True, unique=True, verbose_name='id')
    username = models.CharField(max_length=30, unique=True, null=False, help_text='Логин',
                                error_messages={'unique': "Такой пользователь уже существует!"})
    avatar = models.ImageField(upload_to='images/avatars/', verbose_name='Аватарка')

    def __str__(self):
        return self.username


class Question(models.Model):
    id = models.AutoField(primary_key=True, unique=True, verbose_name='id')
    question_text = models.CharField(max_length=200, verbose_name='Название')
    pub_date = models.DateTimeField(default=datetime.today(), null=False, verbose_name='Дата')
    life_time = models.DateTimeField(default=datetime.today() + timedelta(days=1),
                                     verbose_name='Время жизни',
                                     null=False)
    full_info = models.CharField(max_length=50, null=False, verbose_name='полное описание')
    short_info = models.CharField(max_length=25, null=False, verbose_name='краткое описание')
    question_image = models.ImageField(upload_to='images/questions/', verbose_name='картинка')
    votes = models.IntegerField(default=0, verbose_name='коллво голосов')
    voted_by = models.ManyToManyField(CustomUser, verbose_name='проголосовавшие', blank=True)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def persentc(self):
        return round(100 * self.votes / self.question.votes)

    def __str__(self):
        return self.choice_text

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Question
from django import forms


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'avatar')


class CustomUserChangeForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'avatar')


class AddQuestion(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('question_text', 'full_info', 'short_info', 'question_image')

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import Question, CustomUser, Choice


class Register(CreateView):
    """Класс регистрации юзера"""
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')


def handle_page_not_found(request):
    return redirect('homepage')


class DeleteUserView(LoginRequiredMixin, DeleteView):
    """Класс удаления юзера"""
    login_url = 'login'
    model = CustomUser
    template_name = 'personal_area/delete_user.html'
    success_url = reverse_lazy('index')

    def form_valid(self):
        self.object.delete()


class UpdateUser(LoginRequiredMixin, UpdateView):
    """Класс обновления юзера"""
    login_url = 'login'
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'personal_area/update_user.html'
    success_url = reverse_lazy('personal_area')

    def dispatch(self, request, *args, **kwargs):
        """проверка данных перед ответом """
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        obj = self.get_object()
        if obj.username != self.request.user.username:
            return render(request, '404.html')
        return super(UpdateUser, self).dispatch(request, *args, **kwargs)


class IndexView(ListView):
    """Класс главной страницы"""
    model = Question
    paginate_by = 4
    template_name = 'index.html'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class QuestionFullView(DetailView, LoginRequiredMixin):
    """Класс подробного описания голосования"""
    model = Question
    template_name = 'questions/info_question.html'


class PersonalAreaView(LoginRequiredMixin, ListView):
    """Класс личного кабинета"""
    login_url = 'login'
    model = CustomUser
    template_name = 'personal_area/personal_area.html'


class ResultsView(DetailView, LoginRequiredMixin):
    """Класс просмотра результатов"""
    model = Question
    template_name = 'questions/results_question.html'


def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        redirect('index.html')


def logout_view(request):
    logout(request)
    redirect('index.html')


@login_required
def vote(request, question_id):
    if Question.objects.filter(id=question_id, voted_by=request.user):
        return render(request, 'vote_error.html')
    else:

        question = get_object_or_404(Question, pk=question_id)

        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'questions/info_question.html', {
                'question': question,
                'error_message': 'вы не сделали выбор'
            })
        else:
            current_q = Question.objects.get(id=question_id)
            current_q.voted_by.add(request.user)
            current_q.votes += 1
            current_q.save()
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('result_question', args=(question.id,)))

templates/index.html
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    {% load static %}
    <link rel="stylesheet" href="{% static 'catalog/index.css' %}">
    {%block title%} <title>Дизайн студия</title> {%endblock%}

<link href="../assets/dist/css/bootstrap.min.css">

  </head>
  <body class="d-flex h-100 text-center text-bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link fw-bold py-1 px-0 active" aria-current="page"
           href="{% url 'index' %}">Домашняя страница</a>
        {% if user.is_authenticated %}
          <a class="nav-link fw-bold py-1 px-0" href="{% url 'personal_area' %}">
            Пользователь: {{ request.user.username }}</a>
          <a class="nav-link fw-bold py-1 px-0" href="{% url 'logout' %}">Выход</a>
          {%else%}
          <a class="nav-link fw-bold py-1 px-0" href="{% url 'login' %}">авторизация</a>
          <a class="nav-link fw-bold py-1 px-0" href="{% url 'signup' %}">Регистрация</a>
        {%endif%}
      </nav>
    </div>
  </header>
  {% block content %}
    {% if question_list %}
        <div class="main">
          {% for question in question_list %}
          {% if question.pub_date < question.life_time %}
            <div class="design">
              <p><a href="{% url 'info_question' question.id %}"> Название: {{ question.question_text }}</a></p>
              <img src="{{ question.question_image.url }}" alt="connect" style="max-height:150px">
              <p>Описание: {{ question.short_info }}</p>
              <p><a href="{% url 'result_question' question.id %}"> Результаты опроса: </a></p>
              <p>Варианты ответов: </p>
              {% for choice in question.choice_set.all %}
                <p>{{ choice.choice_text }} -- {{ choice.votes }} голос
                </p>
              {% endfor %}
            </div>
          {% else %}
            {% if user.is_staff %}
              <div class="design">
                <p><a href="{% url 'info_question' question.id %}"> Название: {{ question.question_text }}</a></p>
                <img src="{{ question.question_image.url }}" alt="connect" style="max-height:150px">
                <p>Описание: {{ question.short_info }}</p>
                <p><a href="{% url 'result_question' question.id %}"> Результаты опроса: </a></p>
                <p>Варианты ответов: </p>
                {% for choice in question.choice_set.all %}
                  <p>{{choice.choice_text}} -- {{ choice.votes }} голос</p>
                {% endfor %}
              </div>
            {% endif %}
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}
  <footer class="mt-auto text-white-50">
    <p>Floppa</p>
  </footer>
  {% endblock %}
</div>
</body>
</html>

templates/personal_area/delete_user.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'catalog/delete_user.css' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="signin.css" rel="stylesheet">
  </head>

{% block content %}

<table style="display: flex; justify-content: space-around;">
    <h1>Удаление профиля</h1>
    <p>Вы уверены, что хотите удалить профиль: {{ user.get_username }}?</p>
    <form action="" method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>
    </table>
{% endblock %}

templates/personal_area/personal_area.html
<!doctype html>
<html lang="en" class="h-100">
<head>
<meta charset="utf-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<link rel="stylesheet" href="{% static 'catalog/area.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
{%block title%} <title>Дизайн студия</title> {%endblock%}
<link href="../assets/dist/css/bootstrap.min.css">
<script src='//'></script>
</head>
<body class="d-flex h-100 text-center text-bg-dark">
  <div class="d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header>
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link fw-bold py-1 px-0" aria-current="page" href="{% url 'index' %}">Домашняя страница</a>
        {% if user.is_authenticated %}
          <a class="nav-link fw-bold py-1 px-0 active" href="#">
	          Пользователь: {{ request.user.username }}</a>
          <a class="nav-link fw-bold py-1 px-0" href="{% url 'logout'%}?next={{request.path}}">Выход</a>
          {%else%}
          <a class="nav-link fw-bold py-1 px-0" href="{% url 'login'%}?next={{request.path}}">авторизация</a>
          <a class="nav-link fw-bold py-1 px-0" href="{% url 'signup' %}?next={{request.path}}">Регистрация</a>
          {%endif%}
      </nav>
  </header>
    <div class="main">
      <div class="design">
          <p>Имя: {{ user.get_username }}</p>
          {% if user.avatar %}
          <img src="{{ request.user.avatar.url }}" alt="connect" style="max-height:150px">
          {% endif %}
          <p class="text">Описание: {{ user.user_info }}</p>
          <a href="{% url 'delete_user' user.id %}"><p><strong>Удалить профиль??</strong></p></a>
          <a href="{% url 'update_user' user.id %}"><p><strong>Изменить профиль??</strong></p></a>
        </div>
    </div>
    <footer class="mt-auto text-white-50">
      <p>Floppa</a>.</p>
    </footer>
  </div>
</body>
</html>

templates/personal_area/update_admin.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'catalog/update_user.css' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
<main class="form-signin w-100 m-auto">
<table style="display: flex; justify-content: space-around;">
    <h1>Обновление профиля</h1>
    <p>Следуйте этой форме:</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Обновить заявку</button>
        </form>
    </table>
</main>
  </body>
</html>

templates/personal_area/update_user.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'catalog/update_user.css' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
<main class="form-signin w-100 m-auto">
<table style="display: flex; justify-content: space-around;">
    <h1>Обновление профиля</h1>
    <p>Следуйте этой форме:</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Обновить заявку</button>
        </form>
    </table>
</main>
  </body>
</html>

templates/questions/add_question.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'catalog/add_question.css' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="signin.css" rel="stylesheet">
  </head>

  <body class="text-center">
<main class="form-signin w-100 m-auto">
<table style="display: flex; justify-content: space-around;">
    <h1>Создание заявки</h1>
    <p>Следуйте этой форме:</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
    <input class="w-100 btn btn-lg btn-primary" type="submit">
    </form>
    </table>
    </main>
</form>
</form>

  </body>
</html>

templates/questions/info_question.html
<form action="{% url 'vote' question.id %}" method="post">
    {% csrf_token %}
    {% if question.pub_date < question.life_time or user.is_staff %}
            <img src="{{ question.question_image.url }}" alt="connect" style="max-height:150px">
            <h1>{{question.question_text}}</h1>
            <p><strong>Описание: {{ question.full_info }}</strong></p>
            {% if error_message %}<p><strong> {{error_message}}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
            <input type="submit" value="Vote">
            {% endfor %}
    {% else %}
            <p>Такой заявки нет :(</p>
            <a href="{% url 'index' %}">на главный экран </a>
    {% endif %}
</form>

templates/questions/results_question.html

{% if question.pub_date < question.life_time or user.is_staff %}
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong> {{error_message}}</strong></p>{% endif %}
            <div id="choices_div">
                <ul>
                    {% for choice in question.choice_set.all %}
                    <li>{{ choice.choice_text }} -- {{ choice.votes }} голос({{choice.persentc}}%)</li>
                    {% endfor %}
                </ul>
            </div>
    {% else %}
        <p>Такой заявки нет :(</p>
    {% endif %}
<a href="{% url 'index' %}">на главный экран </a>


templates/vote_error.html
{% block title %}Ошибка{% endblock %}
{% block content %}
  <h1>Вы уже голосовали</h1>
{% endblock %}

users/templates/logget_out.html
{% extends "login.html" %}

{% block content %}
<p>Logged out!</p>

<a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}